config/routes.rb
Rails.application.routes.draw do

   
  devise_for :users
  get "/about_us", to: "home#about_us", as: "about_us"
  get "/contact_us", to: "home#contact_us", as: "contact_us"
  get "/student", to: "home#student", as: "student"
  get "/teacher", to: "home#teacher", as: "teacher"

  resources :books 
  resources :posts
  resources :products

  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	validates :name, presence: true
  validates :price, numericality: true
  before_save :check_title

 # def check_title
 #	if self.title.blank?
 #		self.name = "title"
 #	end
 #end

	
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user

	mount_uploader :image, ImageUploader
	after_destroy :log_destroy_action

	def log_destroy_action
		puts "post is deleted"
	end
	
end

app/models/product.rb
class Product < ApplicationRecord
	validates :name, presence: true

	mount_uploader :image, ImageUploader
	before_save :check_availability

	def check_availability
		if self.description.blank?
			self.description = "this is description"
		end
	end

	# before_validation :check_name
	# before_save :check_price

	# def check_name
	# 	if self.name.blank?
	# 		self.name = "text product"
	# 	end
	# end

	# def check_price
	#	if self.price.present? && self.price.zero?
	# 		self.price = 1
	# 	end
	# end

	def self.class_method
	end

	def instance_method
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :books, dependent: :destroy
  has_many :posts, dependent: :destroy
 				
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :get_book, only: [:show]
  before_action :get_user_book, only: [:edit, :update, :destroy]
  before_action :check_book_user, only: [:edit, :update, :destroy]

  def index
    @books = Book.order(created_at: :desc)
  end
  
  def create
    book = current_user.books.build(book_params)
    if book.save
      redirect_to books_path
    else
      render :new
    end
  end

  def new
    @book = current_user.books.build
  end
  
  def show
  end
  
  def edit
  end

  def update
    if @book.update_attributes(book_params)
      redirect_to books_path
    else
      render :edit
    end
  end
  
  def destroy
    if @book.destroy
      redirect_to books_path
    else
      render :new
    end
  end

  private

  def get_book
    @book = Book.find(params[:id])
  end

  def get_user_book
    @book = current_user.books.find(params[:id])
  end

  def check_book_user
    if @book.user != current_user
      redirect_to books_path
    end
  end

  def book_params
    params.require(:book).permit(:name, :author, :title, :description, :price)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end

	def about_us
	end
	def contact_us
	end
	def student
	end
	def teacher
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except: [:show, :index]
	before_action :get_post, only: [:show, :edit, :update,:destroy]
	before_action :get_user_post, only: [:edit, :update, :destroy]
	before_action :check_post_user, only: [:edit, :update, :destroy]

	def index
		@posts = Post.all
	end

	def create
		@post = current_user.posts.new(post_params)
		# @post = Post.new(post_params)
		if @post.save
			redirect_to posts_path
		else
			render :new
		end

	end
  
  def new
  	@post = current_user.posts.build
  end

  def show
  end

  def edit
  end

  def update
  	if @post.update_attributes(post_params)
  		redirect_to posts_path
  	else
  		render :edit
  	end

  end

  def destroy
  	if @post.destroy
  		redirect_to posts_path
  	else
  		render :new
  	end
  end

  def post_params
  	params.require(:post).permit(:title, :description, :image)
  	# params.require(:post).permit(:description, :user_id)
  end

  def get_post
  	@post=Post.find(params[:id])
  end

  def get_user_post
    @post = current_user.posts.find(params[:id])
  end
  
  def check_post_user
    if @post.user != current_user
      redirect_to posts_path
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :get_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path
    else
      render :new
    end
  end

  def new
    @product = Product.new
  end

  def show
  end

  def edit
  end

  def update
    if @product.update_attributes(product_params)
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
  end

  def product_params
    params.require(:product).permit(:name, :description, :price, :available, :discontinue_on, :image)
  end

  def get_product
    @product = Product.find(params[:id]) rescue nil
    if @product.blank?
      redirect_to products_path
    end
  end
end

app/controllers/users_controller.rb
class UserController < ApplicationController
	def method_name
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/books/edit.html.erb
<%= link_to "Back",books_path %>
<%= form_for @book do |f| %>
	<table>
	<tr>
		<td>Name:</td>
		<td><%= f.text_field :name, placeholder: "Name" %></td>
	</tr>
	<tr>
		<td>Author:</td>
		<td><%= f.text_field :author, placeholder: "author" %></td>
	</tr>
	<tr>
		<td>Title:</td>
		<td><%= f.text_field :title, placeholder: "title" %></td>
	</tr>
	<tr>
		<td>Description:</td>
		<td><%= f.text_field :description,placeholder: "description"%></td>
	</tr>
	<tr>
		<td>Price:</td>
		<td><%= f.text_field :price,placeholder: "Price"%></td>
	</tr>
	<tr>
		<td><%= f.submit %></td>
	</tr>
</table>
<%end%>

app/views/books/index.html.erb
<% if user_signed_in? %>
  <%= link_to "create_new_book", new_book_path%>
<% end %>
<ul>
  <% @books.each do |book| %>
    <li>
      <table>
        <tr>
          <td>Name:</td>
          <td><%= book.name %></td>
        </tr>
        <tr>
          <td>Author:</td>
          <td><%= book.author %></td>
        </tr>
        <tr>
          <td>Title:</td>
          <td><%= book.title %></td>
        </tr>
        <tr>
          <td>Description:</td>
          <td><%= book.description %></td>
        </tr>
        <tr>
          <td>Price:</td>
          <td><%= book.price %></td>
        </tr>
        <tr>
          <td>User email:</td>
          <td><%= book.user.email rescue "" %></td>
        </tr>
      </table>
			<%= link_to "Show", book_path(book.id) %>
      <% if user_signed_in? && book.user == current_user %>
			  <%= link_to "Edit", edit_book_path(book.id) %>
			  <%= link_to "Delete",book_path(book.id), method: :delete,data: {confirm: "are you sure?"} %>
      <% end %>
		</li>
	<%end%>
</ul>

app/views/books/new.html.erb
<%= form_for @book do |f| %>
<table>
	<tr>
		<td>Name:</td>
		<td><%= f.text_field :name, placeholder: "Name" %></td>
	</tr>
	<tr>
		<td>Author:</td>
		<td><%= f.text_field :author, placeholder: "author" %></td>
	</tr>
	<tr>
		<td>Title:</td>
		<td><%= f.text_field :title, placeholder: "title" %></td>
	</tr>
	<tr>
		<td>Description:</td>
		<td><%= f.text_area :description,placeholder: "description"%></td>
	</tr>
	<tr>
		<td>Price:</td>
		<td><%= f.text_field :price,placeholder: "Price"%></td>
	</tr>
	<tr>
		<td><%= f.submit %></td>
	</tr>
</table>
<%end%>

app/views/books/show.html.erb
<%= link_to "back",books_path %>
<table border="1">
	<tr>
		<td>Name:</td>
		<td><%= @book.name %></td>
	</tr>
	<tr>
		<td>Author:</td>
		<td><%= @book.author %></td>
	</tr>
	<tr>
		<td>Title:</td>
		<td><%= @book.title %></td>
	</tr>
	<tr>
		<td>Description:</td>
		<td><%= @book.description %></td>
	</tr>
	<tr>
		<td>Price:</td>
		<td><%= @book.price %></td>
	</tr>
</table>	
	<% if user_signed_in? && book.user == current_user %>
		<%= link_to "Edit",edit_book_path(@book.id) %>
		<%= link_to "Delete",book_path(@book.id),method: :delete,data:{ confirm: "are you sure?"} %>
<% end %>
<%= link_to "New Book",new_book_path %>

app/views/home/about_us.html.erb
<a href="<%= root_path %>">home</a>
about_us

app/views/home/contact_us.html.erb
<%= link_to "Home", root_path %>
<a href="<%=student_path%>">Student </a>
<a href="/about_us">about us</a>
contact_us
<form method="post">
<b>User Login</b></br>
<table>
	<tr>
		<td>First name:</td>
		<td><input type="text" name="First name"></td>
	</tr>
	<tr>
		<td>Last name:</td>
		<td><input type="text" name="Last name"></td>
	</tr>	
	<tr>
		<td>Email:</td>
		<td><input type="Email" name="Email"></td>
	</tr>
	<tr>
		<td>Address</td>
		<td><input type="text" name="address"></td>
	</tr>
	<tr>
		<td>Number:</td>
		<td><input type="Number" name="number"></td>
	</tr>
	<tr>
	<td><input type="submit"  >
</table>
<form>

app/views/home/index.html.erb
<a href="/contact_us">Contact Us</a>
<h1 id="home_page">this is home page</h1>
<a href="/teacher">Teacher Module</a>
<div class="homm">
	<ul>
		<li><a href="<%= student_path %>">Student Module</a></li>
		<li>Teacher Module</li>
		<li>center manager module</li>
		<% if user_signed_in? %>
		<li><a href="/contact_us">Contact Us</a>
		<% end %>
		<li><a href="<%= about_us_path %>">About Us</a></li>
	</ul>
	
</div>

app/views/home/student.html.erb
student_module
<a href="/contact_us">Contact Us</a>
<%= link_to "Home", root_path %>
<!--<div class="header">
<span class="a"> Student's account</span> <span class="b">welcome student</span><span><button>logout</button></span>

</div>-->

app/views/home/teacher.html.erb
hello teacher
<h3>Teacher Login</h3>
<%= link_to "home",root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnlineCenterManagement</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <% if user_signed_in? %>
      <%= link_to "logout", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "login", new_user_session_path %> | <%= link_to "sign up", new_user_registration_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<%= link_to "back",posts_path %>
<%= form_for @post do |f| %>
  Title: <%= f.text_area :title, placeholder: "title" %><br/>
	Description: <%= f.text_area :description, placeholder: "description" %><br/>
	Image: <%= f.text_area :image %>
<%= f.submit %>
<%end%>

app/views/posts/index.html.erb
<% if user_signed_in? %>
<%= link_to "create_new_post", new_post_path %><br/>
<% end %>
<% @posts.each do |post| %>
  Title:<%= post.title %><br/>
  Description:<%= post.description %><br/>
  Image:
  <% if post.image.present? %>
    <%= image_tag post.image.url, width: 100, height: 50 %><br/>
  <% end %>
  <%= link_to "Show", post_path(post.id) %>
  <% if user_signed_in? && post.user == current_user %>
    <%= link_to "Edit", edit_post_path(post.id) %>
    <%= link_to "delete", post_path(post.id) , method: :delete, data: { confirm: "are you sure?" } %>
  <% end %>
<% end %>

app/views/posts/new.html.erb
<%= link_to "back",posts_path %>
<%= form_for @post do |f| %>
  <%#= f.hidden_field :user_id, value: current_user.id %>
  Title<%= f.text_area :title, placeholder: "title" %><br/>
	Description:<%= f.text_area :description, placeholder: "description" %><br/>
	Image<%= f.file_field :image %><br/>
<%= f.submit %>
<%end%>

app/views/posts/show.html.erb
<%= link_to "back",posts_path %>
Title:<%= @post.title %>
Description:<%= @post.description %>
Image:<%= @post.image %>
	<% if user_signed_in? && @post.user == current_user %>
		<%= link_to "Edit", edit_post_path(@post.id) %>
		<%= link_to "delete", post_path(@post.id), method: :delete, data: {confirm: "are you sure"} %>
  <%end%>

app/views/products/edit.html.erb
<%= link_to "back", products_path %>
<%= form_for @product do |f| %>
	Name:<%= f.text_field :name, placeholder: "name"%><br/>
	Description:<%= f.text_area :description, placeholder: "description" %><br/>
	Price:<%= f.text_field :price, placeholder: "price" %> <br/>
	Available:<%= f.text_field :available, placeholder: "available" %><br/>
  Discontinue_on:<%= f.date_field :discontinue_on %><br/>
  Image:<%= f.file_field :image %>
  <%= f.submit %>
	<% end %>

app/views/products/index.html.erb
<%= link_to "new", new_product_path %>
<% @products.each do |product| %>
	Name:<%= product.name %><br/>
  Description:<%= product.description %><br/>
  Price<%= product.price %><br/>
  Available:<%= product.available %><br/>
  Discontinue_on:<%= product.discontinue_on %></br>
  Image:
<% if product.image.present? %>
  <%= image_tag product.image.url, width: 50, height: 80 %><br/>
<% end %></br>
  <%= link_to "Edit", edit_product_path(product.id) %><br/>
  <%= link_to "show", product_path(product.id) %>
  <%= link_to "delete", product_path(product.id), method: :delete, data: {confirm: "are you sure"} %>
<% end %>

app/views/products/new.html.erb
<%= form_for @product do |f| %>
  <% if @product.errors.any? %>
    <% @product.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  <% end %>
  
	Name:<%= f.text_field :name, placeholder: "name"%><br/>
	Description:<%= f.text_area :description, placeholder: "description" %><br/>
	Price:<%= f.text_field :price, placeholder: "price" %> <br/>
	Available:<%= f.text_field :available, placeholder: "available" %><br/>
  Discontinue_on:<%= f.date_field :discontinue_on %><br/>
  Image:<%= f.file_field :image %>
  <%= f.submit %>
<% end %>

app/views/products/show.html.erb
<%= link_to "back", products_path %>
	Name:<%= @product.name %><br/>
	Description:<%= @product.description %><br/>
	Price:<%= @product.price %><br/>
	Available:<%= @product.available %>
	Discontinue_on:<%= @product.discontinue_on %>
	Image:<%= @product.image %>
<%= link_to "Edit", edit_product_path(@product.id) %>
<%= link_to "delete", product_path(@product.id), method: :delete, data: {confirm: "are u sure?"} %>